#!/bin/bash

versions=('3.2.8' '3.3.8')

switcher=`which asdf`
if [[ $switcher = *[!\ ]* ]]; then
  verb="local ruby"
else
  switcher=`which rbenv`
  if [[ $switcher = *[!\ ]* ]]; then
    verb="local"
  else
    switcher=`which rvm`
    if [[ $switcher = *[!\ ]* ]]; then
      verb="use"
    else
      echo "Please install asdf, rbenv, or rvm"
      exit 1
    fi
  fi
fi

case "$1" in
  appraisal-install)
    for version in ${versions[@]}
    do
      echo "Appraisal install for Ruby $version"
      eval "$switcher $verb $version"
      bundle exec appraisal install
    done
    ;;

  appraisal-spec)
    for version in ${versions[@]}
    do
      echo "Run appraisal specs with Ruby $version"
      eval "$switcher $verb $version"
      bundle exec appraisal rspec
    done
    ;;

  bundle)
    for version in ${versions[@]}
    do
      echo "Bundle for Ruby $version"
      eval "$switcher $verb $version"
      gem list --local bundler | grep bundler || gem install --no-ri --no-rdoc bundler
      bundle install --path vendor
      bundle update
    done
    ;;

  spec)
    for version in ${versions[@]}
    do
      echo "Run specs with Ruby $version"
      eval "$switcher $verb $version"
      bundle exec rspec spec
    done
    ;;

  *)
    echo $"Usage: $0 {bundle|spec|appraisal-install|appraisal-spec}"
    exit 1
esac

exit 0
